French number token updates
mapbox/geocoder-abbreviations pull request #84
Opened 2020-10-02 15:37 UTC by ilissablech

Use french words for numbers:)

2020-10-09 20:51 UTC, aarthykc commented on tokens/fr.json
> -            "général",
Was removing this intentional?

2020-10-09 20:58 UTC, ilissablech commented on tokens/fr.json
> -            "général",
@aarthykc As everything is evaluated without accents these are not needed. Could happily keep them in. Does the carmen side need or benefit from the accents?

2020-10-09 21:02 UTC, aarthykc requested changes
@ilissablech had questions about some of the tokens you added here. Could you add more details to the PR body about why some of these were added? Could you also touch upon why some of the accents were dropped for a couple of these replacements?

2020-10-09 21:03 UTC, aarthykc commented on tokens/fr.json
> +            "Marechal"
Why "Marechal" instead of "Maréchal"?

2020-10-09 21:05 UTC, aarthykc commented on tokens/fr.json
> +        "full": "rond-point",
It shouldn't matter if it's capitalised or not from carmen's perspective, any reason why these were changed?

2020-10-12 13:20 UTC, ilissablech commented
> @ilissablech had questions about some of the tokens you added here. Could you add more details to the PR body about why some of these were added? Could you also touch upon why some of the accents were dropped for a couple of these replacements?

@aarthykc I reverted the instances where accents were dropped. I also removed the `passage commun` token, as we should handle that situation in pt2itp. Thanks for calling that out. Many other words were added in to aid in matching addresses to networks, found during our orphan analysis sprint. As we now added in functionality in pt2itp using spanBoundaries I updated a few of those token sets to include other commonly seen variations of tokens (ie. all the variations of `major general`.

2020-10-12 22:26 UTC, aarthykc commented on tokens/fr.json
> +        "canonical": "mgen",
@ilissablech are we certain that the canonical representation for major general is mgen?

2020-10-12 22:27 UTC, aarthykc commented on tokens/fr.json
> -        "canonical": "l gen",
@ilissablech are we certain that the canonical representation for leiutenant general is lgen and not l gen?

2020-10-13 15:18 UTC, aarthykc approved these changes
👌🏽 thanks for working through the feedback @ilissablech!

2020-10-13 15:23 UTC, merged