Spanish tokens
mapbox/geocoder-abbreviations pull request #85
Opened 2020-10-05 21:04 UTC by ilissablech

2020-10-09 19:20 UTC, apendleton requested changes
@ilissablech added a bunch of specific questions, but in general I'm not sure I understand the motivations for several of the changes here, so a bit more detail either in response or in the PR body about why some of these changes are necessary would be super helpful. In particular, a bunch of token replacements that used to apply in all Spanish-speaking countries are now only applied in Spain, including some I'm quite sure are used elsewhere (like "Calle"). It would be good to understand what the objective was there, so we can figure out how to achieve it without breaking address builds in other Spanish-speaking countries.

2020-10-09 19:20 UTC, apendleton commented on tokens/es.json
> -            "Carrera"
Why was this removed?

2020-10-09 19:20 UTC, apendleton commented on tokens/es.json
> +        "onlyCountries": ["es"]
Why is this replacement now only being applied in Spain? The net effect will be that the abbreviation for (effectively) "street" will now no longer be applied to addresses in Mexico, Chile, Argentina, etc. That doesn't seem like behavior we want?

2020-10-09 19:20 UTC, apendleton commented on tokens/es.json
> -            "Cl Quarter"
Why was this removed?

2020-10-09 19:20 UTC, apendleton commented on tokens/es.json
> +            "francisco"
What's the rationale for doing this with a token replacement, vs. with a synonym on the affected features? Is this common enough that we want to be proactively applying it as a replacement to every query we encounter?

2020-10-09 19:20 UTC, apendleton commented on tokens/es.json
> +        "onlyCountries": ["es"]
Why is this now being country-restricted?

2020-10-09 19:20 UTC, apendleton commented on tokens/es.json
> +        "onlyCountries": ["es"]
why is this now country-restricted?

2020-10-09 19:20 UTC, apendleton commented on tokens/es.json
> +    },
Why replace the old replacement with this one? Seems like the main differences are that this one is declared to be a regular expression (but isn't?), and that it's now country-restricted.

2020-10-09 19:20 UTC, apendleton commented on tokens/es.json
> +            "(l|d) ([aeiouhy][^ ]+)"
Hm, does this replacement do anything? The version of a similar replacement in France detects a version that has a space, and deletes the space, but this version detects a version that has a space, and outputs a version that still has a space. I think I'm probably missing something?

2020-10-09 19:54 UTC, ilissablech commented on tokens/es.json
> -            "Carrera"
This was not removed but moved further down to the token set of carrera/cr.

2020-10-09 19:54 UTC, ilissablech commented on tokens/es.json
> -            "Cl Quarter"
I had added this in in a [previous PR ](https://github.com/mapbox/geocoder-abbreviations/pull/81)but this token set is no longer needed. Also, the `Cl` in this set conflicts with `Calle`.

2020-10-09 19:58 UTC, ilissablech commented on tokens/es.json
> +    },
I refactored PT2ITP on how regexes are used and are now also using them for multi-words. The `full` token will be replaced with the `canonical` and then tokens will be applied. Does marking this as regex:true interfere with how carmen evaluates this?

2020-10-09 20:19 UTC, ilissablech commented on tokens/es.json
> +            "(l|d) ([aeiouhy][^ ]+)"
Ah. Thank you for calling that out. I resolved that in a different way & meant to remove from the token list.

2020-10-09 20:59 UTC, apendleton commented on tokens/es.json
> +    },
@ilissablech regex replacements are more computationally expensive than non-regex replacements in Carmen, so if we don't have to use the regex logic, that'd be ideal (also, just from a tagging semantics perspective, it isn't a regex, so marking it as such is surprising). Also: `regex: true` implies different semantics with respect to regex-specific characters, so for example, `.` in most token replacements is a period but in regexes is any character, and most replacements that have periods just mean them to be periods. `regex: true` is a way to signal both that the thing is a regex, and that you actually want any special characters to be interpreted according to their regex meaning (or, if you don't, that you've manually escaped them already).

It's not necessarily safe to just throw all multi-word replacements into a regex without making sure they conform to regex semantics, and I'd prefer not to have to force a requirement going forward that all multi-word token replacements need to adopt regex semantics (and escape their periods, etc.). If you want to use regular expressions in your implementation for both circumstances, it seems like a better approach might be to handle this on the pt2itp side: use a regular expression if regex=true **or** spanBoundaries>1, and in the latter case, if regex=False, ensure that the replacement has been properly escaped before using it (so, replace any periods with `\.` etc.).

2020-10-12 19:44 UTC, ilissablech commented on tokens/es.json
> +    },
@apendleton I've made updates to PT2ITP to pull in spanBoundaries properly, instead of relying on regex unnecessary. Thanks for call this out.

2020-10-12 21:42 UTC, apendleton approved these changes
Looks good. Thanks for the changes. If you get a chance, I meant to ask on the first round about the same issue @aarthykc raised in the France one, which was to keep the diacritical marks in these unless there's a specific reason to delete them (e.g., on "Rùa") -- I think it would probably be good to mirror that here as well since that's the correct spelling, but it's not a huge deal either way (Carmen should be able to abstract over presence/absence of diacritics in most circumstances). Going to go ahead and approve and then leave it to your discretion whether to make that additional change.

2020-10-12 21:57 UTC, merged